<?php

return [
    'permissions' => [
        'dashboard.view',
        'users.view',
        'users.create',
        'users.update',
        'users.delete',
        'roles_permissions.view',
        'roles_permissions.update',
        'transactions.view',
        'transactions.create',
        'transactions.update',
        'transactions.delete',
        'transactions.import',
        'transactions.export',
        'categories.view',
        'categories.create',
        'categories.update',
        'categories.delete',
        'reports.view',
        'documents.view',
        'documents.create',
        'documents.delete',
        'documents.download',
        'announcements.view',
        'announcements.create',
        'announcements.update',
        'announcements.delete',
        'settings.view',
        'settings.update',
        'api.users.view',
        'api.transactions.view',
        'api.transactions.create',
    ],
    'roles' => [
        'admin' => ['*'],
        'staff' => [
            'dashboard.view',
            'transactions.view',
            'transactions.create',
            'transactions.update',
            'transactions.import',
            'transactions.export',
            'categories.view',
            'categories.create',
            'categories.update',
            'reports.view',
            'documents.view',
            'documents.create',
            'documents.download',
            'announcements.view',
            'api.transactions.view',
            'api.transactions.create',
        ],
    ],
    'transaction_types' => [
        'income' => 'Income',
        'expense' => 'Expense',
    ],
    'payment_methods' => [
        'cash' => 'Cash',
        'bank_transfer' => 'Bank Transfer',
        'cheque' => 'Cheque',
        'online' => 'Online Payment',
        'wallet' => 'Digital Wallet',
    ],
    'setting_defaults' => [
        'app.company_name' => 'Nepali Finance Management System',
        'app.company_email' => 'info@example.com',
        'app.company_phone' => '+977-1-0000000',
        'app.address' => 'Kathmandu, Nepal',
        'app.currency_symbol' => 'NPR',
        'mail.notification_email' => 'accounts@example.com',
        'mail.send_transaction_notifications' => '0',
        'reports.default_locale' => 'en',
    ],
];
